### ISSUE TITLE
CheckList

### ISSUE THREAD

**Issue by Prz901** [Prz901/foody#1]
- [x] Montar relacionamento das tabelas
- [x] Baixar o projeto do adônis
- [x] Baixar o projeto do bootsrap
- [x] Integrar o bootsrap com edge do adônis
- [x] Criar o Seed do administrador
- [x] Criar o Login do administrador
- [x] Criar o logout do administrador
- [x] Criar a pagina de cadastro de categorias
- [x] Criar a pagina de cadastro de produtos

- [x] Criar o login do cliente
- [x] Criar o logout do cliente
- [x] Listar os produtos
- [x] Adicionar os produtos no checkout
- [x] CRUD de Pedido
- [x] Listar pedidos por mês por usuário
- [x] Admin pode alterar status do pedido
- [x] Inserir imagem de produto
- [ ] Recuperação de senha
- [x] Colocar nome da categoria na listagem produto
- [ ] Validar campo de preço
- [x] Adaptar a Mudi (cor, logo e nome)
